language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=VirgilSDK.xcodeproj
  - IOS_TEST_APP_SCHEME="TestSDKApp"
  - IOS_FRAMEWORK_SCHEME="VirgilSDK iOS"
  - IOS_SDK=iphonesimulator10.0
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     APP_SCHEME="$IOS_TEST_APP_SCHEME"    SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
    - DESTINATION="OS=9.0,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     APP_SCHEME="$IOS_TEST_APP_SCHEME"    SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
language: objective-c
script:
  - carthage update
  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES APPLICATION_IDENTITY_TYPE="$APPLICATION_IDENTITY_TYPE" APPLICATION_ID="$APPLICATION_ID" APPLICATION_PRIVATE_KEY_PASSWORD="$APPLICATION_PRIVATE_KEY_PASSWORD" APPLICATION_PRIVATE_KEY_BASE64="$APPLICATION_PRIVATE_KEY_BASE64" APPLICATION_TOKEN="$APPLICATION_TOKEN" MAILINATOR_TOKEN="$MAILINATOR_TOKEN" build test | xcpretty && xcodebuild -verbose -project "$PROJECT" -scheme "$APP_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES APPLICATION_IDENTITY_TYPE="$APPLICATION_IDENTITY_TYPE" APPLICATION_ID="$APPLICATION_ID" APPLICATION_PRIVATE_KEY_PASSWORD="$APPLICATION_PRIVATE_KEY_PASSWORD" APPLICATION_PRIVATE_KEY_BASE64="$APPLICATION_PRIVATE_KEY_BASE64" APPLICATION_TOKEN="$APPLICATION_TOKEN" MAILINATOR_TOKEN="$MAILINATOR_TOKEN" build test | xcpretty;
    else
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO APPLICATION_IDENTITY_TYPE="$APPLICATION_IDENTITY_TYPE" APPLICATION_ID="$APPLICATION_ID" APPLICATION_PRIVATE_KEY_PASSWORD="$APPLICATION_PRIVATE_KEY_PASSWORD" APPLICATION_PRIVATE_KEY_BASE64="$APPLICATION_PRIVATE_KEY_BASE64" APPLICATION_TOKEN="$APPLICATION_TOKEN" MAILINATOR_TOKEN="$MAILINATOR_TOKEN" build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)