language: objective-c
osx_image: xcode8.3
env:
  global:
  - DOC_BRANCH=master
  - LC_CTYPE=en_US.UTF-8
  - PROJECT=VirgilSDK.xcodeproj
  - IOS_FRAMEWORK_SCHEME="VirgilSDK iOS"
  - IOS_SDK=iphonesimulator10.3
  matrix:
    - DESTINATION="OS=10.3,name=iPhone SE"     SCHEME="$IOS_FRAMEWORK_SCHEME"    SDK="$IOS_SDK"    RUN_TESTS="YES"    PUBLISH_DOCS="NO"

before_install:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
language: objective-c
script:
  - carthage update --platform iOS --no-use-binaries;
  # Build Framework
  - xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES APPLICATION_IDENTITY_TYPE="$APPLICATION_IDENTITY_TYPE" APPLICATION_ID="$APPLICATION_ID" APPLICATION_PRIVATE_KEY_PASSWORD="$APPLICATION_PRIVATE_KEY_PASSWORD" APPLICATION_PRIVATE_KEY_BASE64="$APPLICATION_PRIVATE_KEY_BASE64" APPLICATION_TOKEN="$APPLICATION_TOKEN" MAILINATOR_TOKEN="$MAILINATOR_TOKEN" CARDS_SERVICE_URL="$CARDS_SERVICE_URL" CARDS_SERVICE_RO_URL="$CARDS_SERVICE_RO_URL" IDENTITY_SERVICE_URL="$IDENTITY_SERVICE_URL" REGISTRATION_AUTHORITY_URL="$REGISTRATION_AUTHORITY_URL" clean build-for-testing | xcpretty;
  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release GCC_GENERATE_TEST_COVERAGE_FILES=YES test-without-building | xcpretty;
    fi
after_success:
  - if [ $RUN_TESTS == "YES" ]; then
      bash <(curl -s https://codecov.io/bash);
    fi
  - if [ "${PUBLISH_DOCS}" == "YES" ] && [ "${TRAVIS_BRANCH}" == "${DOC_BRANCH}" ]; then
      ./CI/publish-docs.sh;
    fi
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "${TRAVIS_BUILD_DIR}/docs"
  on:
    branch: ${DOC_BRANCH}
