language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=VirgilSDK.xcworkspace
  - IOS_FRAMEWORK_SCHEME="VirgilSDK iOS"
  - IOS_SDK=iphonesimulator10.0
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
    # - DESTINATION="OS=9.0,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"

before_install:
  - pod repo update
script:
  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild\
          -workspace "$WORKSPACE"\
          -scheme "$SCHEME"\
          -sdk "$SDK"\
          -destination "$DESTINATION"\
          -configuration Release\
          ONLY_ACTIVE_ARCH=NO\
          ENABLE_TESTABILITY=YES\
          APPLICATION_IDENTITY_TYPE="$APPLICATION_IDENTITY_TYPE"\
          APPLICATION_ID="$APPLICATION_ID"\
          APPLICATION_PRIVATE_KEY_PASSWORD="$APPLICATION_PRIVATE_KEY_PASSWORD"\
          APPLICATION_PRIVATE_KEY_BASE64="$APPLICATION_PRIVATE_KEY_BASE64"\
          APPLICATION_PUBLIC_KEY_BASE64="$APPLICATION_PUBLIC_KEY_BASE64"\
          APPLICATION_TOKEN="$APPLICATION_TOKEN"\
          test | xcpretty;
    else
      xcodebuild\
          -workspace "$WORKSPACE"\
          -scheme "$SCHEME"\
          -sdk "$SDK"\
          -destination "$DESTINATION"\
          -configuration Debug\
          ONLY_ACTIVE_ARCH=NO\
          APPLICATION_IDENTITY_TYPE="$APPLICATION_IDENTITY_TYPE"\
          APPLICATION_ID="$APPLICATION_ID"\
          APPLICATION_PRIVATE_KEY_PASSWORD="$APPLICATION_PRIVATE_KEY_PASSWORD"\
          APPLICATION_PRIVATE_KEY_BASE64="$APPLICATION_PRIVATE_KEY_BASE64"\
          APPLICATION_PUBLIC_KEY_BASE64="$APPLICATION_PUBLIC_KEY_BASE64"\
          APPLICATION_TOKEN="$APPLICATION_TOKEN"\
          build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  # - if [ $POD_LINT == "YES" ]; then
  #     pod lib lint;
  #   fi